version: '2.1'
orbs:
  aws-s3: circleci/aws-s3@3.0
jobs:
  test:
    docker:
      - image: 'circleci/node:17.1-browsers'
    steps:
      - checkout
      - run: npm install && npx nx test
  build:
    docker:
      - image: 'circleci/node:17.1-browsers'
    steps:
      - checkout
      - run: npm install && npx nx build
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: dist/apps/next/.next/
          to: 's3://futbolpro-ci-cd/'
workflows:
  test-build-deploy:
    jobs:
      - test
      - build:
          requires:
              - test

